# Generated by Django 2.0.13 on 2019-12-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
