# Generated by Django 2.0.13 on 2019-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191213_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text=' at least 3 character. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True)),
                ('email', models.EmailField(help_text='Required. Inform a valid email address.', max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('Phone', models.IntegerField(help_text='write like this format: 09xxxxxxxx')),
                ('birth_date', models.DateField(help_text='Format: YYYY-MM-DD')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperUser')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
