# Generated by Django 2.0.13 on 2019-12-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20191219_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserProfile',
        ),
    ]
